server {
    listen 5055;
    root .;          # ← Racine = dossier courant (WEBGRP)
    index index.html;
    
    location /session.py {
        root ./storage;  # ← Cherche dans storage/
        cgi .py /usr/bin/python3;
    }
}