#!/usr/bin/env python3
import os, sys
sys.stdout.write("Content-Type: text/html\r\n\r\n")
sys.stdout.flush()
print("<html><body>")
print("<h1>CGI Session Test</h1>")
print(f"<p>REQUEST_METHOD: {os.environ.get('REQUEST_METHOD', 'not set')}</p>")
print(f"<p>QUERY_STRING: {os.environ.get('QUERY_STRING', 'not set')}</p>")
print(f"<p>HTTP_COOKIE: {os.environ.get('HTTP_COOKIE', 'not set')}</p>")
print(f"<p>CONTENT_TYPE: {os.environ.get('CONTENT_TYPE', 'not set')}</p>")
print(f"<p>CONTENT_LENGTH: {os.environ.get('CONTENT_LENGTH', 'not set')}</p>")
print(f"<p>SERVER_NAME: {os.environ.get('SERVER_NAME', 'not set')}</p>")
print(f"<p>SERVER_PORT: {os.environ.get('SERVER_PORT', 'not set')}</p>")
print(f"<p>PATH_INFO: {os.environ.get('PATH_INFO', 'not set')}</p>")
print(f"<p>SCRIPT_NAME: {os.environ.get('SCRIPT_NAME', 'not set')}</p>")
if os.environ.get('REQUEST_METHOD') == 'POST':
    length = int(os.environ.get('CONTENT_LENGTH', 0) or 0)
    body = sys.stdin.read(length)
    print(f"<p>BODY: {body}</p>")
print("</body></html>")
