server {
    server_name 127.0.0.1;
    listen 5050;
    root ./public/website1;
    index index.html;
    max_client_body_size 2K;
    allow GET DELETE;
    autoindex on;
    error_page 404 ./public/error_pages/404.html;
    error_page 405 ./public/error_pages/405.html;
    error_page 413 ./public/error_pages/413.html;
    upload ./public/website2/;

    location /home {
        allow GET POST DELETE;
        root ./public/website1/;
        index index.html;
        autoindex on;
    }

    location /aboutt {
        allow GET;
        root ./public/website1/;
        index aboutt.html;
    }

    location /not {
        allow DELETE;
        root ./public/website1/;
        index about.html;
    }

    location /mcha {
        allow GET DELETE;
        root ./public/website2/;
        index about.html;
    }

    location /upload {
        allow GET POST;
        root ./public/website2/;
        index index.html;
        upload ./;
    }

    location /sub {
        allow GET;
        root ./public/website1/;
        index index.html;
        autoindex on;
    }

    location /empty {
        allow GET POST;
        root ./public/website1/;
        index empty.html;
    }

    location / {
        allow GET DELETE;
        root ./public/website1/;
        index index.html;
        autoindex on;
    }
}

server {
    server_name 127.0.0.1;
    listen 5051;
    root ./public/website1;
    index index.html;
    max_client_body_size 30000;
    allow GET DELETE;
    autoindex on;
    error_page 404 ./public/error_pages/404.html;
    upload ./public/website2/;
    cgi .php /usr/bin/php-cgi;

    location /upload {
        allow GET POST;
        root ./public/website2/;
        index index.html;
        upload ./;
    }

    location /mcha {
        allow GET DELETE;
        root ./public/website2/;
        index about.html;
    }

    location / {
        allow GET DELETE;
        root ./public/website1/;
        index index.html;
        autoindex on;
    }
}

server {
    server_name 127.0.0.1;
    listen 5052;
    autoindex on;
    root ./storage;
    index session.py;
    cgi .py /usr/bin/python3;

    location / {
        allow GET POST;
        root ./storage;
        cgi .py /usr/bin/python3;
    }

    location /perl {
        allow GET POST;
        root ./CGI/CGI-bin;
        cgi .pl /usr/bin/perl;
    }
}