server {
    listen 5050;
    root ./public/website1;
    index index.html;
    
    location /old-page {
        redirect 301 /new-page;
    }
    
    location /new-page {
        root ./public/website1;
        index new.html;
    }
}
#test redirect 
#step1:     echo '<h1>New Page - Redirection worked!</h1>' > public/website1/new.html
#step2:     url -v http://localhost:5050/old-page
#Expected output: HTTP/1.1 301 Moved Permanently
#                 Location: /new-page