server {
    server_name 127.0.0.1;
    listen 127.0.0.1:8080;
    autoindex on;
    root ./var/www;
    index index.html;
    max_client_body_size 100M;


    cgi .py /usr/bin/python3;

    location / {
        allow GET;
        root ./var/www/;
        index index.html;
        autoindex on;
    }

}
