


server {
    server_name 127.0.0.1;
    listen 5050;
    max_client_body_size 100M;
    allow GET POST DELETE;
    autoindex on;
    upload ./var/www/storage;
    root ./var/www;
    index index.html;
    cgi .py /usr/bin/python3;



    location / {
        root var/www/website3;
        index test_website.py;
        allow GET POST;
        cgi .py /bin/python3;
        # cgi .php /bin/php;
        # cgi .sh /bin/sh;
    }

    location /video {
        root /var/ww/website3;
        index video.mp4;
        autoindex on;
        allow GET;
    }

    location /delete {
        root var/www/storage;
        index invalid;
        autoindex on;
        allow DELETE GET;
    }

    location /dire {
        root var/www;
        index invalid;
        allow GET;
        autoindex on;
    }

    location /upload {
        allow GET POST;
        root ./var/www/storage;
        index index.html;
        upload ./;
    }


    location /empty {
        allow GET POST;
        root ./var/www/website1/;
        index empty.html;
    }

}
