


server {
    server_name 127.0.0.1;
    listen 127.0.0.1:8080;
    max_client_body_size 100M;
    allow GET POST DELETE;
    autoindex on;
    upload /upload;
    root var/www;
    index index.html;

    cgi .py /usr/bin/python3;
    cgi .sh /bin/bash;
    cgi .php /usr/bin/php-cgi;

    error_page 404 ./errors/404.html;
    error_page 403 ./errors/403.html;
    error_page 405 ./errors/405.html;
    error_page 408 ./errors/408.html;
    error_page 409 ./errors/409.html;
    error_page 411 ./errors/411.html;
    error_page 413 ./errors/413.html;
    error_page 414 ./errors/414.html;
    error_page 415 ./errors/415.html;
    error_page 500 ./errors/500.html;
    error_page 501 ./errors/501.html;
    error_page 502 ./errors/502.html;
    error_page 504 ./errors/504.html;

    location / {
        root var/www/website3;
        index test_website.py;
        allow GET POST;
        cgi .py /bin/python3;
    }

    location /video {
        root var/www/website3;
        index video.mp4;
        autoindex on;
        allow GET;
    }

    location /delete {
        root var/www/upload/;
        index invalid;
        allow DELETE GET;
    }

    location /dire {
        root var/www;
        index invalid;
        allow GET POST;
        autoindex on;
    }

    location /upload {
        allow GET POST;
        root var/www;
        index index.html;
        autoindex on;
        upload /upload;
    }

}



server {
    server_name 127.0.0.1;
    listen 127.0.0.1:5052;
    autoindex on;
    root ./var/www;
    index index.html;
    max_client_body_size 100M;


    cgi .py /usr/bin/python3;
    cgi .php /usr/bin/php;
    cgi .sh /usr/bin/sh;

    location / {
        allow GET;
        root ./var/www/;
        index index.html;
        autoindex on;
    }

    location /cgi-bin{
        allow GET POST;
        upload ../upload;
        root ./var/www/cgi-bin/;
        index session.sh;
        cgi .sh /usr/bin/sh;
        cgi .php /usr/bin/php;
        cgi .py /usr/bin/python3;
        autoindex on;

    }

}

